#:import TitleScreen title_screen.title_screen
#:import LoginScreen login_screen.login_screen
#:import OTPScreen otp_screen.otp_screen
#:import GameScreen game_screen.game_screen

ScreenManager:
    id: manager

    LoadScreen:
    TitleScreen:
    LoginScreen:
    OTPScreen:
    GameScreen:

<LoadScreen>:
    id: load_screen
    name: "load_screen"

    Label:
        id: load_screen_label
        name: "load_screen_label"
        text: "Loading..."