
<LoginScreen@LoadScreen>:
    id: login_screen
    name: "login_screen"

    MDRectangleFlatButton:
        id: google_login_button
        name: 'google_login_button'
        text: "Login with Google Account"
        pos_hint: {'center_x': .4, 'center_y': .4}
        theme_text_color: 'Custom'
        text_color: (100 / 255.0, 100 / 255.0, 100 / 255.0, .8)
        on_release: root.start_google_login()
